  [[secrets.passthrough]]
    type   = "raw"
    target = "monkci-secrets.toml"
    value  = """
  [extend]
    path = "/monkci-secrets.toml"

  [[rules]]
    id       = "HIMANSHU_GYBE"
    regex    = '''HIMANSHU_GYBE!'''
    keywords = ["himanshu_gybe"]
    …
  [[rules]]
    id       = "akshit-persoal-rule"
    regex    = '''AKSHIT-GYBE!'''
    keywords = ["akshit-gybe"]
    …
  """
